PATCH  http://localhost:3000/posts
Content-Type: application/json
{
  "id":7,
  "title": "Hello World NESTJS with TS",
  "postType": "post",
  "slug": "nest-js-with-ts",
  "status": "draft",
  "content": "Hello World",
    // "tags": ["hello", "world"],
  "metaOptions":{
    "metaValue":"{\"sideBar\":true,\"footer\":true}"
    },
    "authorId":1,
    "tags":[6,4]
}