POST http://localhost:3000/users/create
Content-Type: application/json

{
    "firstName": "John Doe",
    "lastName": "John Doe",
    "email": "mark@doe.com",
    "password": "Password123"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer 
    
    
{
    "users":[
{
    "firstName": "John Doe",
    "email": "oh@doe.com",
    "lastName": "John Doe",
    "password": "Password123"
},
{
    "firstName": "John Doe",
    "lastName": "John Doe",
    "email": "jon@doe.com",
    "password": "Password123"
}
]
}