POST http://localhost:3000/users/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6Im1hcmtAZG9lLmNvbSIsImlhdCI6MTczMzc0OTc0NiwiZXhwIjoxNzMzNzUzMzQ2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Rw9SnV-ToiJVWo3NCwuaqS5rCWYFQ11cJWs96drE-tU

{
    "firstName": "John Doe",
    "lastName": "John Doe",
    "email": "mark@doe.com",
    "password": "Password123"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6Im1hcmtAZG9lLmNvbSIsImlhdCI6MTczMzc0OTc0NiwiZXhwIjoxNzMzNzUzMzQ2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Rw9SnV-ToiJVWo3NCwuaqS5rCWYFQ11cJWs96drE-tU
    
    
{
    "users":[
{
    "firstName": "John Doe",
    "email": "oh@doe.com",
    "lastName": "John Doe",
    "password": "Password123"
},
{
    "firstName": "John Doe",
    "lastName": "John Doe",
    "email": "jon@doe.com",
    "password": "Password123"
}
]
}